-- v0.8.9 (original): Ensure existing policy_rules.action values match uppercase CHECK.
-- v0.8.10: This UPDATE was moved into migration 20260405200008 (before the ADD CONSTRAINT)
-- to prevent CHECK constraint failure on non-empty databases. Retained as no-op for
-- migration history continuity.
-- (no-op: data migration now happens in 20260405200008)
